[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
project = "Hi9cu3A6LHB8kuVXFEH8RDCDWSLxSyoEG5bCo9RJ6b7X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/edward/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
