[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting_system = "FDgFxeYS7Bw1NCx38qwg6xnR8ELicuGKGHcT6aDwUDBX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
